//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFGUSEVDEMOEX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoExamEntities : DbContext
    {
        private static DemoExamEntities _context;
        public DemoExamEntities()
            : base("name=DemoExamEntities")
        {
        }

        public static DemoExamEntities GetContext()
        {
            if( _context == null )
                _context = new DemoExamEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Partners_import_> Partners_import_ { get; set; }
        public virtual DbSet<Partners_product_import_> Partners_product_import_ { get; set; }
        public virtual DbSet<Product_import_> Product_import_ { get; set; }
        public virtual DbSet<Product_type_import_> Product_type_import_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
