//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFGUSEVDEMOEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_product_import_
    {
        public int partner_products_import_ID { get; set; }
        public Nullable<int> Products_import_name { get; set; }
        public Nullable<int> Name_partner_import { get; set; }
        public Nullable<int> quantity_import { get; set; }
        public Nullable<System.DateTime> Date_import { get; set; }
    
        public virtual Partners_import_ Partners_import_ { get; set; }
        public virtual Product_import_ Product_import_ { get; set; }
    }
}
