//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFGUSEVDEMOEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_import_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners_import_()
        {
            this.Partners_product_import_ = new HashSet<Partners_product_import_>();
        }
    
        public int type_partner_ID { get; set; }
        public string type_partner { get; set; }
        public string name_partner { get; set; }
        public string director_partners { get; set; }
        public string email_partners { get; set; }
        public string number_partners { get; set; }
        public string adress_partners { get; set; }
        public Nullable<double> INN_partners { get; set; }
        public Nullable<double> raring_partners { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners_product_import_> Partners_product_import_ { get; set; }
    }
}
