//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFGUSEVDEMOEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_import_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_import_()
        {
            this.Partners_product_import_ = new HashSet<Partners_product_import_>();
        }
    
        public int type_products_ID { get; set; }
        public Nullable<int> type_products { get; set; }
        public string name_products { get; set; }
        public Nullable<int> articul_products { get; set; }
        public Nullable<int> minprice_products { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners_product_import_> Partners_product_import_ { get; set; }
        public virtual Product_type_import_ Product_type_import_ { get; set; }
    }
}
