//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFGUSEVDEMOEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_type_import_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_type_import_()
        {
            this.Product_import_ = new HashSet<Product_import_>();
        }
    
        public int type_product_import_ID { get; set; }
        public string type_product_import_name { get; set; }
        public Nullable<int> kafe_type_product_import { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_import_> Product_import_ { get; set; }
    }
}
